version: "3.9"
name: ccp_web_demo

networks:
  ccp-network:
    driver: bridge



services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres-cloud_demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cloud_demo
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - ccp-network

  web:
    image: ccp_web
    container_name: ccp_web_demo
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    networks:
      - ccp-network
    ports:
      - "3000:${PORT}"
    command: yarn start
    depends_on:
      - db