version: "3.9"
# name: cloud_computing_web_demo
name: nestjs_online_booking_movie

networks:
  movie_booking-network:
    driver: bridge



services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres_db_mv_booking
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cloud_mv_booking_db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    networks:
      - movie_booking-network

  web:
    image: nestjs_online_movie_booking_web
    container_name: nestjs_online_movie_booking_image
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    networks:
      - movie_booking-network
    ports:
      - "3000:${PORT}"
    command: yarn start
    depends_on:
      - db


