version: "3.9"
name: rest-api-online_booking_movie
networks:
  movie_booking-network:
    driver: bridge
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres_db_mv_booking
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hor9999
      POSTGRES_DB: cloud_mv_booking_db
    expose:
      - "5434"
    ports:
      - "5434:5434"
    command: -p 5434
    volumes:
      - ./backup/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./script/restore.sh:/docker-entrypoint-initdb.d/restore.sh
    networks:
      - movie_booking-network
  web:
    image: nestjs_online_movie_booking_web
    container_name: nestjs_online_movie_booking_image
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    networks:
      - movie_booking-network
    ports:
      - "5000:${PORT}"
    command: yarn start
    depends_on:
      - db